Fix for Ruby 2.7. Also updates gem/bundler versions.
This change AVOIDS the actual error:

NoMethodError: undefined method `new' for BigDecimal:Class
   ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>',

without really fixing it, by limiting our requires of ActiveSupport to just the inflector methods that this gem actually uses.